### ISSUE TITLE
How exactly is Nodetrout.Internal.Content.getAcceptable supposed to work?

### ISSUE THREAD

**Issue by iostat** [nsaunders/purescript-nodetrout#7]
I'm currently trying to write a simple API server using Nodetrout. My endpoints return `text/plain`, I have a type for it, MimeRender/AllMimeRender instances, etc. and everything compiles.

I do a simple request to my endpoint with `Accept: text/plain`. Find that the endpoint gets called and ran, but then the server returns a `406 Not Acceptable`. After some tracing I see that it's because my requested `Content-Type` is neither `application/json` nor `text/html`, which are the only MimeTypes the function at hand would allow as Preferred/Required MIMEs.

I see two issues here:
1) Why can't you just construct a `MediaType` from the all the MIMEs in `Accept` if it gets used down the line in `serveAcceptable` anyway?
2) Why is my endpoint being evaluated if its result can't be served? Seems to me like that would break API expectations especially in state-modifying endpoints.

**Comment by nsaunders** [comment]
Hi there, I'm sorry to hear that you've run into a use case that hasn't been solved yet.

To answer your main question, `getAcceptable` is about parsing the request's `Accept` header. It's definitely incomplete (even a bit naïve), but at the time that I wrote it I wasn't aware of any libraries that could help with content negotiation or `Accept` header parsing. If you are aware of such a library existing today or would like to help improve the `getAcceptable` function to address more use cases, please let me know!

An easy and immediate workaround, I think, would be to short-circuit the content negotiation altogether by omitting the `Accept` header from your request.

Your other point about the `406 Not Acceptable` response being rendered too late in the request cycle is completely valid and something that should be addressed, and I will take care of that as soon as I can (unless someone else solves it first, of course!)

**Comment by iostat** [comment]
Hey @nsaunders, thanks for the reply! I was just hoping to understand if there's any particular reason (i.e., some kind of underlying bug in node-http, etc.) for the Accept limitation to JSON and HTML, but it seems like you're saying it's arbitrary at the moment. If you'd like, I can submit a PR with a stopgap that wraps all the split-on-comma values in a `MediaType` which should solve the basic use case (i.e., actually serving stuff that's not JSON or HTML), and defer the more complicated (e.g., parameters like utf-8 in `text/plain;utf-8`) for later. I can also take a stab at not serving "unacceptable" endpoints as well.
